<%@ include file="/WEB-INF/pages/common/taglib.jsp"%>
<!DOCTYPE html>
<html>
<head>
<%@ include file="/WEB-INF/pages/common/css.jsp"%>
<title>Jobbifi Terms of Service</title>
</head>
<body>
	<%@ include file="/WEB-INF/pages/common/header.jsp"%>
	<div class="container">
	<div class="col-md-2"></div>
		<div class="col-md-8">
			<div class="row">
			<br/><br/><br/>
			<center>
				<h1>PRIVACY POLICY</h1>
			</center>
<p>
This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures to make the terms of this policy binding.
</p>
<p>
At www.jobbifi.com, data protection is a matter of trust and your privacy is very important to us. We use your personal information only in the manner set out in this Privacy Policy. Please read this privacy policy to learn more about our information gathering and dissemination practices.
</p>
<p>
This Privacy Policy explains how we gather personal information, classified as mandatory or optional as part of the normal operation of our services; and use, disclose and protect such information through the Site. This detailed privacy policy enables you to take informed decisions in dealings with us. Our parent, subsidiaries and joint ventures operate under similar privacy practices subject to the requirements of applicable law.
</p>
<p>
By registering with us, you acknowledge your acceptance of the terms of this Privacy Policy, expressly consent to our use and disclosure of your personal information in accordance with this Privacy Policy and that any personal information provided by you through us is provided under a lawful contract. This Privacy Policy is incorporated into and subject to the terms of the User Agreement. 
</p>
<p>
We are extremely proud of our commitment to protect your privacy. We value your trust in us. We work hard to earn your confidence so that you can enthusiastically use our services and recommend your friends and family to participate in dealing with us. Please read the following policy to understand how your personal information will be treated as you make full use of our Site.
</p>
<p>
Our privacy policy is subject to change at any time without notice. To make sure you are aware of any changes, please review this policy periodically.
</p>
<p>
1. INFORMATION WE COLLECT:
</p>
<p>
1.1 When you register with us, you provide us information about yourself - your username, email address, password etc. If you correspond with us by e-mail, we may retain the content of your e-mail messages, your e-mail address, and our responses. Additionally, we store information about users' contacts when users manually enter contact e-mail addresses or transfer contact information from other online social networks. We also collect general information about your use of our services.
</p>
<p>
2. INFORMATION WE COLLECT AUTOMATICALLY WHEN YOU USE OUR SERVICES:
</p>
<p>
2.1 When you access or use our Services, we automatically collect information about you, including:
</p>
<p>
a) Usage Information: When you send or receive messages via our Services, we collect information about these messages, including the time, date, sender and recipient. We also collect information about the number of messages sent and received between you and your friends and which friends you exchange messages with most frequently. If you choose to post messages on our message boards, chat rooms or other message areas or leave feedback for other users, we retain this information as necessary to resolve disputes, provide customer support and troubleshoot problems as permitted by law. If you send us personal correspondence, such as emails or letters, or if other users or third parties send us correspondence about your activities or postings on the Site, we may collect such information into a file specific to you.
</p>
<p>
b) Log Information: We log information about your use of our website, including your browser type and language, access times, pages viewed, your IP address and the website you visited before navigating to our website.
</p>
<p>
c) Device Information: We may collect information about the device you use to access our Services, including the hardware model, operating system and version, unique device identifier, phone number, International Mobile Equipment Identity ("IMEI") and mobile network information. 
</p>
<p>
d) Location Information: With your consent, we may collect information about the location of your device to facilitate your use of certain features of our Services, determine the speed at which your device is traveling, add location-based filters (such as local weather), and for any other purposes.
</p>
<p>
e) Information Collected by Cookies and Other Tracking Technologies: We use various technologies to collect information, and this may include sending cookies to you. A "cookie" is a small data file transferred to your computer's hard drive that allows a Website to respond to you as an individual, gathering and remembering information about your preferences in order to tailor its operation to your needs, likes and dislikes. Overall, cookies are safe, as they only identify your computer to customize your Web experience. Accepting a cookie does not provide us access to your computer or any Personally Identifiable Information about you, other than the information you choose to share. Other servers cannot read them, nor can they be used to deliver a virus. Most browsers automatically accept cookies, but you can usually adjust yours (Microsoft Internet Explorer, Firefox or Google Chrome) to notify you of cookie placement requests, refuse certain cookies, or decline cookies completely. If you turn off cookies completely, there may be some website features that will not be available to you, and some Web pages may not display properly. To support the personalized features of our website (such as your country and language codes and browsing functions) we must send a cookie to your computer's hard drive and/or use cookie-based authentication to identify you as a registered website user. We do not, however, use so-called "surveillance" cookies that track your activity elsewhere on the Web. We may also collect information using web beacons (also known as "tracking pixels"). 
</p>
<p>
3. INFORMATION SHARED DURING TRANSACTION:
</p>
<p>
3.1 You agree that you will enter into transactions with third parties through our website and will share your personally identifiable information with them for easy completion of the transaction. You hereby expressly agree that we shall not be involved or held liable for any breach of the privacy or security of that data. The said breach, if any, shall be a matter of dispute between you and the third party and we shall not be held liable or be issued a notice for the same.  
</p>
<p>
3.2 We STRONGLY recommend that you should be careful and vigilant while disclosing your personally identifiable details with your transaction partner. Please do not disclose your bank and account details to anyone through our website or to any individual whom you have met through our website.  
</p>
<p>
4. HOW WE USE YOUR INFORMATION:
</p>
<p>
4.1 We use the personal information we collect to fulfill your requests for services, improve our services, contact you, conduct research, and provide anonymous reporting for internal and external clients.
</p>
<p>
4.2 By providing us your e-mail address, you consent to us using the e-mail address to send you our website and services related notices, including any notices required by law, in lieu of communication by postal mail. You also agree that we may send notifications of activity on our website to the e-mail address you give us, in accordance with any applicable privacy settings. We may use your e-mail address to send you other messages, such as newsletters, changes to our features, or other information. If you do not want to receive optional e-mail messages, you may modify your settings to opt out.
</p>
<p>
4.3 Our settings may also allow you to adjust your communications preferences. If you do not wish to receive promotional email messages from us, you may opt out by following the unsubscribe instructions in those emails. If you opt out, you will still receive non-promotional emails from us about your account and our Services.
</p>
<p>
4.4 All messages you record or send using our services will be stored on our server and will be downloaded to a temporary cache on the recipient's device for playback. When a sender of a message marks a message for deletion, that message will no longer be available to recipients via our website server, but it may still be accessible in the temporary caches of recipients who have already received the message. Messages marked for deletion will not be deleted immediately from our server, but will instead be deleted upon the next deletion event, which will be scheduled on a periodic basis.
</p>
<p>
4.5 Following termination or deactivation of your services, we may (but is under no obligation to) retain your information for archival purposes. Furthermore, after termination or deactivation of your services, messages that you have not deleted may be retained so that recipients may continue to access them. We will not publicly disclose any of your personally identifiable information other than as described in this Privacy Policy.
</p>
<p>
4.6 We do not, as a matter of course, access or monitor messages recorded or sent using our service. However, we reserve the right (but have no obligation) to access, review, and/or monitor the content you record or send using our website, at our sole discretion, for any reason or no reason at all, and we reserve the right to remove any such content or messages in our sole discretion, including, but not limited to, if we believe such action is necessary (a) to conform to the law, comply with legal process served on us or our affiliates, or investigate, prevent, or take action regarding suspected or actual illegal activities; (b) to enforce this policy, to take precautions against liability, to investigate and defend ourselves against any third-party claims or allegations, to assist government enforcement agencies, or to protect the security or integrity of our website; or (c) to exercise or protect the rights, property, or personal safety of the website, our users, or others.
</p>
<p>
5. HOW WE SHARE YOUR INFORMATION:
</p>
<p>
5.1 As a matter of policy, we will not sell or rent information about you and we will not disclose information about you in a manner inconsistent with this Privacy Policy except as required by law or government regulation. We cooperate with law enforcement inquiries, as well as other third parties, to enforce laws such as those regarding intellectual property rights, fraud and other personal rights.
</p>
<p>
5.2 We will not share the personal information we collect about you with any third party for their own marketing purposes without your consent. We may share your data with our services providers who process your personal information to provide services to us or on our behalf. We have contracts with our service providers that prohibit them from sharing the information about you that they collect or that we provide to them with anyone else, or using it for other purposes.
</p>
<p>
5.3 You may decline to submit Personally Information through the Services, in which case we may not be able to provide certain services to you. If you do not agree with our Privacy Policy or Terms of Service, please discontinue use of our Service; your continued usage of the Service will signify your assent to and acceptance of our Privacy Policy and Terms of Use.
</p>
<p>
5.4 WE CAN (AND YOU AUTHORIZE US TO) DISCLOSE ANY INFORMATION ABOUT YOU TO LAW ENFORCEMENT, OTHER GOVERNMENT OFFICIALS, ANY LAWSUIT OR ANY OTHER THIRD PARTY THAT WE, IN OUR SOLE DISCRETION, BELIEVE NECESSARY OR APPROPRIATE IN CONNECTION WITH AN INVESTIGATION OF FRAUD, INTELLECTUAL PROPERTY INFRINGEMENT, OR OTHER ACTIVITY THAT IS ILLEGAL OR MAY EXPOSE US, OR YOU, TO LIABILITY.
</p>
<p>
6. ENSURING INFORMATION IS ACCURATE AND UP-TO-DATE
</p>
<p>
6.1 We take reasonable precautions to ensure that the Personal Information we Collect, Use and Disclose is complete, relevant and up-to-date. However, the accuracy of that information depends to a large extent on the information you provide. That's why we recommend that you:
</p>
<p>
a) Let us know if there are any errors in your Personal Information; and
</p>
<p>
b) Keep us up-to-date with changes to your Personal Information such as your name or address. 
</p>
<p>
7. HOW WE PROTECT YOUR INFORMATION:
</p>
<p>
7.1 We are very concerned about safeguarding the confidentiality of your personally identifiable information. We employ administrative, physical and electronic measures designed to protect your information from unauthorized access.
</p>
<p>
7.2 By using this website or the Services or providing Personal Information to us, you agree that we can communicate with you electronically regarding security, privacy, and administrative issues relating to your use of this website or Services.
</p>
<p>
7.3 We use commercially reasonable physical, managerial, and technical safeguards to preserve the integrity and security of your Personal Information. We cannot, however, ensure or warrant the security of any information you transmit to us and you do so at your own risk. Using unsecured wi-fi or other unprotected networks to submit messages through the Service is never recommended. Once we receive your transmission of information, we make commercially reasonable efforts to ensure the security of our systems. However, please note that this is not a guarantee that such information may not be accessed, disclosed, altered, or destroyed by breach of any of our physical, technical, or managerial safeguards. If we learn of a security systems breach, then we may attempt to notify you electronically so that you can take appropriate protective steps.
</p>
<p>
7.4 Notwithstanding anything to the contrary in this Policy, we may preserve or disclose your information if we believe that it is reasonably necessary to comply with a law, regulation or legal request; to protect the safety of any person; to address fraud, security or technical issues; or to protect our rights or property. However, nothing in this Policy is intended to limit any legal defenses or objections that you may have to a third party, including a government's, request to disclose your information.
</p>
<p>
8. YOUR CHOICES ABOUT YOUR INFORMATION:
</p>
<p>
8.1 You have several choices regarding use of information on our Services:
</p>
<p>
(a) Email Communications: We will periodically send you free newsletters and e- mails that directly promote the use of our website, or Services. When you receive newsletters or promotional communications from us, you may indicate a preference to stop receiving further communications from us and you will have the opportunity to “opt-out” by following the unsubscribe instructions provided in the e-mail you receive or by contacting us directly. Despite your indicated e-mail preferences, we may send you service related communications, including notices of any updates to our Terms of Use or Privacy Policy.
</p>
<p>
(b) Changing or Deleting Your Personal Information: You may change any of your personal information in your Account by emailing us at support@jobbifi.com or by visiting the website and following the directions therein. You may request deletion of your personal information by us, and we will use commercially reasonable efforts to honor your request, but please note that we may be required to keep such information and not delete it (or to keep this information for a certain time, in which case we will comply with your deletion request only after we have fulfilled such requirements). When we delete any information, it will be deleted from the active database, but may remain in our archives. We may also retain your information for fraud prevention or similar purposes.
</p>
<p>
8.2 You may, of course, decline to submit personally identifiable information through the website, in which case, we may not be able to provide certain services to you. You can review and correct the information about you that we keep on file by editing your account settings or by contacting us directly at support@jobbifi.com
</p>
<p>
9. CHILDREN'S PRIVACY:
</p>
<p>
 Our services are available only to persons who can form a legally binding contract under the Indian Contract Act, 1872. Protecting the privacy of young children is especially important. Thus, we do not knowingly collect or solicit personal information from anyone under the age of 18 or knowingly allow such persons to register. If you are under 18, please do not attempt to register for the Service or send any information about yourself to us, including your name, address, telephone number, or email address. No one under the age of 18 may provide any personal information for accessing the Service. If an individual under the age of 18 wishes to purchase or sell a product/item on the Site then such purchase or sale may be made by their legal guardian or parents who have registered as users of the Site and who can form legally binding contract under the Indian Contract Act, 1872. In the event that we learn that we have collected personal information from a child under age 18, we will delete that information as quickly as possible. If you believe that we might have any information from or about a child under 18, please contact us through our privacy help page.
</p>
<p>
10. MERGER AND ACQUISITIONS:
</p>
<p>
In case of a merger or acquisition, we reserve the right to transfer all the information, including personally identifiable information, stored with us to the new entity or company thus formed. Any change in the website's policies and standing will be notified to you through email. 
</p>
<p>
11. LINKS TO THIRD PARTY WEBSITES:
</p>
<p>
Our website contains links to other websites. The fact that we link to a website is not an endorsement, authorization or representation of our affiliation with that third party. We do not exercise control over third party websites. These other websites may place their own cookies or other files on your computer, collect data or solicit personally identifiable information from you. Other sites follow different rules regarding the use or disclosure of the personally identifiable information you submit to them. We encourage you to read the privacy policies or statements of the other websites you visit.
</p>
<p>
12. ADVERTISING:
</p>
<p>
Advertisers and advertising networks place ads (including sponsored links in search results) on our website. These companies, as well as data analytics companies who service them, may use cookies, pixel tags, mobile device IDs and other similar technologies to collect data about you when you visit our website. They use the data to enable them to track your activity across various sites where they display ads and record your activities, so they can show ads that they consider relevant to you. You may opt-out of receiving targeted online advertising from advertising networks that is delivered on our website. 
</p>
<p>
13. NOTIFICATION PROCEDURES:
</p>
<p>
It is our policy to provide notifications, whether such notifications are required by law or are for marketing or other business related purposes, to you via e-mail notice, written or hard copy notice, or through conspicuous posting of such notice on the website, as determined by us in our sole discretion. We reserve the right to determine the form and means of providing notifications to you, provided that you may opt out of certain means of notification as described in this Privacy Policy.
</p>
<p>
14. SURVEYS:
</p>
<p>
We also use surveys to collect information about our users. From time to time, we request users' input in order to evaluate potential features and services. The decision to answer a survey is completely yours. We use information gathered from surveys to improve our services.
</p>
<p>
15. OPTING OUT OF INFORMATION SHARING:
</p>
<p>
15.1 We understand and respect that not all users may want to allow us to share their information with other select users or companies. If you do not want us to share your information, please contact us through the Contact Us page, and we will remove your name from lists we share with other users or companies as soon as reasonably practicable or you can also click on unsubscribe. When contacting us, please clearly state your request, including your name, mailing address, email address and phone number.
</p>
<p>
15.2 However, under the following circumstances, we may still be required to share your personal information:
</p>
<p>
a) If we respond to court orders or legal process, or if we need to establish or exercise our legal rights or defend against legal claims.
</p>
<p>
b) If we believe it is necessary to share information in order to investigate, prevent or take action regarding illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, violations of our Terms of Use or as otherwise required by law.
</p>
<p>
c) If we believe it is necessary to restrict or inhibit any user from using any of our Site, including, without limitation, by means of "hacking" or defacing any portion thereof.
</p>
<p>
16. INVITATION SERVICES:
</p>
<p>
We may offer you the opportunity to use our invitation services so that you can tell your family members and friends about us. The service will enable you to import at your direction your contact list from certain email services that you may be using and to send an email on your behalf from your email address, inviting your family member and friends to try the services offered by our website. The information you provide will be used solely to facilitate your sending of the invitation and will not be stored or used by us for any other purpose. If you are a recipient of an invitation and have elected to opt out from receiving any further invitations from us, we will retain your email address solely for the purposes of honoring your opt-out further invitations.
</p>
<p>
17. PHISHING OR FALSE EMAILS:
</p>
<p>
If you receive an unsolicited email that appears to be from us or one of our members that requests personal information (such as your credit card, login, or password), or that asks you to verify or confirm your account or other personal information by clicking on a link, that email was likely to have been sent by someone trying to unlawfully obtain your information, sometimes referred to as a "phisher" or "spoofer." We do not ask for this type of information in an email. Do not provide the information or click on the link. Please contact us at support@jobbifi.com if you get an email like this.
</p>
<p>
18. CHANGES TO OUR PRIVACY POLICY:
</p>
<p>
18.1 We may update this Privacy Policy and information security procedures from time to time. If these privacy and/or information security procedures materially change at any time in the future, we will post the new changes conspicuously on the website to notify you and provide you with the ability to opt out in accordance with the provisions set forth above.
</p>
<p>
18.2 Continued use of our website and Service, following notice of such changes shall indicate your acknowledgement of such changes and agreement to be bound by the terms and conditions of such changes.
</p>
<p>
19. BREACH OF PRIVACY POLICY:
</p>
<p>
We reserve the right to terminate or suspend any account or delete certain contents from any profile or public domain within the ambit of this website if the said account or content is found to be in violation of our privacy policy. We sincerely request you to respect privacy and secrecy concerns of others. The jurisdiction of any breach or dispute shall be determined in accordance with the terms of use of the website.
</p>
<p>
20. NO RESERVATIONS:
</p>
<p>
We do not accept any reservation or any type of limited acceptance of our privacy policy. You expressly agree to each and every term and condition as stipulated in this policy without any exception whatsoever. 
</p>
<p>
21. NO CONFLICT:
</p>
<p>
The policy constitutes a part of the user terms. We have taken utmost care to avoid any inconsistency or conflict of this policy with any other terms, agreements or guidelines available on our website. In case there exists a conflict, we request you to kindly contact us for the final provision and interpretation.  
</p>
<p>
22. CONTACT US:
</p>
<p>
If you have any questions about this Privacy Policy, our practices relating to the website, or your dealings with us, please contact us at support@jobbifi.com.
					</div>
		</div>
		<div class="col-md-2"></div>
	</div>
	<%@ include file="/WEB-INF/pages/common/footer.jsp"%>
	<%@ include file="/WEB-INF/pages/common/js.jsp"%>
	<script type="text/javascript">
</script>
</body>
</html>