# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='mailer.proto',
  package='',
  serialized_pb='\n\x0cmailer.proto\"8\n\tAttribute\x12\x1c\n\x04type\x18\x01 \x02(\x0e\x32\x0e.AttributeType\x12\r\n\x05value\x18\x02 \x02(\t\"N\n\x05\x45mail\x12\x18\n\x04type\x18\x01 \x02(\x0e\x32\n.EmailType\x12\x11\n\trecipient\x18\x02 \x02(\t\x12\x18\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\n.Attribute*\xed\x01\n\tEmailType\x12 \n\x1cNEW_REGISTRATION_INTERVIEWER\x10\x00\x12\x13\n\x0f\x46ORGOT_PASSWORD\x10\x01\x12\x14\n\x10PASSWORD_UPDATED\x10\x02\x12\x16\n\x12NEW_MOCK_INTERVIEW\x10\x03\x12\x1a\n\x16MOCK_INTERVIEW_UPDATED\x10\x04\x12\x0e\n\nBID_PLACED\x10\x05\x12\x0f\n\x0bNEW_MESSAGE\x10\x06\x12\x0f\n\x0bNEW_DISPUTE\x10\x07\x12\x14\n\x10NEW_FUND_DEPOSIT\x10\x08\x12\x17\n\x13NEW_FUND_WITHDRAWAL\x10\t*\x9a\x04\n\rAttributeType\x12\x18\n\x14SUPPORT_REQUEST_NAME\x10\x00\x12\x19\n\x15SUPPORT_REQUEST_EMAIL\x10\x01\x12\x1b\n\x17SUPPORT_REQUEST_MESSAGE\x10\x02\x12\x19\n\x15INTERVIEW_INTERVIEWEE\x10\x03\x12\x13\n\x0fINTERVIEW_TITLE\x10\x04\x12\r\n\tUSER_TYPE\x10\x05\x12\x0e\n\nBID_BIDDER\x10\x06\x12\x0f\n\x0b\x42ID_MESSAGE\x10\x07\x12\r\n\tBID_PRICE\x10\x08\x12\x0c\n\x08\x42ID_DATE\x10\t\x12\x12\n\x0e\x44ISPUTE_AMOUNT\x10\n\x12\x13\n\x0f\x44ISPUTE_MESSAGE\x10\x0b\x12\x15\n\x11\x44ISPUTE_DISPUTEBY\x10\x0c\x12\x1b\n\x17\x44ISPUTE_INTERVIEW_TITLE\x10\r\x12\x17\n\x13\x44ISPUTE_DISPUTEWITH\x10\x0e\x12\x10\n\x0c\x44ISPUTE_USER\x10\x0f\x12\x14\n\x10\x44ISPUTE_DISPUTER\x10\x10\x12\x0e\n\nDISPUTE_ID\x10\x11\x12\x15\n\x11INTERVIEWER_EMAIL\x10\x12\x12\x16\n\x12PASSWORD_RESET_URL\x10\x13\x12\r\n\tUSER_NAME\x10\x14\x12\x12\n\x0eMESSAGE_SENDER\x10\x15\x12\x14\n\x10MESSAGE_RECEIVER\x10\x16\x12\x13\n\x0fMESSAGE_CONTENT\x10\x17\x12\x0f\n\x0b\x46UND_AMOUNT\x10\x18\x42\x1d\n\x13\x63om.interview.protoB\x06Mailer')

_EMAILTYPE = descriptor.EnumDescriptor(
  name='EmailType',
  full_name='EmailType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='NEW_REGISTRATION_INTERVIEWER', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FORGOT_PASSWORD', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PASSWORD_UPDATED', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NEW_MOCK_INTERVIEW', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MOCK_INTERVIEW_UPDATED', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BID_PLACED', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NEW_MESSAGE', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NEW_DISPUTE', index=7, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NEW_FUND_DEPOSIT', index=8, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NEW_FUND_WITHDRAWAL', index=9, number=9,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=155,
  serialized_end=392,
)


_ATTRIBUTETYPE = descriptor.EnumDescriptor(
  name='AttributeType',
  full_name='AttributeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='SUPPORT_REQUEST_NAME', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SUPPORT_REQUEST_EMAIL', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SUPPORT_REQUEST_MESSAGE', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INTERVIEW_INTERVIEWEE', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INTERVIEW_TITLE', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='USER_TYPE', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BID_BIDDER', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BID_MESSAGE', index=7, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BID_PRICE', index=8, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BID_DATE', index=9, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DISPUTE_AMOUNT', index=10, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DISPUTE_MESSAGE', index=11, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DISPUTE_DISPUTEBY', index=12, number=12,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DISPUTE_INTERVIEW_TITLE', index=13, number=13,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DISPUTE_DISPUTEWITH', index=14, number=14,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DISPUTE_USER', index=15, number=15,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DISPUTE_DISPUTER', index=16, number=16,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DISPUTE_ID', index=17, number=17,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INTERVIEWER_EMAIL', index=18, number=18,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PASSWORD_RESET_URL', index=19, number=19,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='USER_NAME', index=20, number=20,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MESSAGE_SENDER', index=21, number=21,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MESSAGE_RECEIVER', index=22, number=22,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MESSAGE_CONTENT', index=23, number=23,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FUND_AMOUNT', index=24, number=24,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=395,
  serialized_end=933,
)


NEW_REGISTRATION_INTERVIEWER = 0
FORGOT_PASSWORD = 1
PASSWORD_UPDATED = 2
NEW_MOCK_INTERVIEW = 3
MOCK_INTERVIEW_UPDATED = 4
BID_PLACED = 5
NEW_MESSAGE = 6
NEW_DISPUTE = 7
NEW_FUND_DEPOSIT = 8
NEW_FUND_WITHDRAWAL = 9
SUPPORT_REQUEST_NAME = 0
SUPPORT_REQUEST_EMAIL = 1
SUPPORT_REQUEST_MESSAGE = 2
INTERVIEW_INTERVIEWEE = 3
INTERVIEW_TITLE = 4
USER_TYPE = 5
BID_BIDDER = 6
BID_MESSAGE = 7
BID_PRICE = 8
BID_DATE = 9
DISPUTE_AMOUNT = 10
DISPUTE_MESSAGE = 11
DISPUTE_DISPUTEBY = 12
DISPUTE_INTERVIEW_TITLE = 13
DISPUTE_DISPUTEWITH = 14
DISPUTE_USER = 15
DISPUTE_DISPUTER = 16
DISPUTE_ID = 17
INTERVIEWER_EMAIL = 18
PASSWORD_RESET_URL = 19
USER_NAME = 20
MESSAGE_SENDER = 21
MESSAGE_RECEIVER = 22
MESSAGE_CONTENT = 23
FUND_AMOUNT = 24



_ATTRIBUTE = descriptor.Descriptor(
  name='Attribute',
  full_name='Attribute',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='Attribute.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='Attribute.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=16,
  serialized_end=72,
)


_EMAIL = descriptor.Descriptor(
  name='Email',
  full_name='Email',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='Email.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='recipient', full_name='Email.recipient', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='Email.data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=74,
  serialized_end=152,
)

_ATTRIBUTE.fields_by_name['type'].enum_type = _ATTRIBUTETYPE
_EMAIL.fields_by_name['type'].enum_type = _EMAILTYPE
_EMAIL.fields_by_name['data'].message_type = _ATTRIBUTE
DESCRIPTOR.message_types_by_name['Attribute'] = _ATTRIBUTE
DESCRIPTOR.message_types_by_name['Email'] = _EMAIL

class Attribute(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ATTRIBUTE
  
  # @@protoc_insertion_point(class_scope:Attribute)

class Email(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EMAIL
  
  # @@protoc_insertion_point(class_scope:Email)

# @@protoc_insertion_point(module_scope)
